// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35yARJck6QivoMcU1TfX4czxrZcMsq7Q',
    appId: '1:357214509875:web:835288306dbdd929d8bc46',
    messagingSenderId: '357214509875',
    projectId: 'food-store-12f0f',
    authDomain: 'food-store-12f0f.firebaseapp.com',
    storageBucket: 'food-store-12f0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtifa6WBPR6wes2-W8e0KUOBqfEM4zKEc',
    appId: '1:357214509875:android:c22a77baae26ee2bd8bc46',
    messagingSenderId: '357214509875',
    projectId: 'food-store-12f0f',
    storageBucket: 'food-store-12f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzvD5w7hkcI4lr9PPjYayjqLQgJajVlDQ',
    appId: '1:357214509875:ios:f238c3ba64b5c353d8bc46',
    messagingSenderId: '357214509875',
    projectId: 'food-store-12f0f',
    storageBucket: 'food-store-12f0f.appspot.com',
    iosBundleId: 'com.example.foodStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzvD5w7hkcI4lr9PPjYayjqLQgJajVlDQ',
    appId: '1:357214509875:ios:9b0458755d7f155cd8bc46',
    messagingSenderId: '357214509875',
    projectId: 'food-store-12f0f',
    storageBucket: 'food-store-12f0f.appspot.com',
    iosBundleId: 'com.example.foodStore.RunnerTests',
  );
}
